//Auto generated by a roslyn source generator
namespace StrideSaber.Testing.Generated
{
	//Source type is LibEternal.Generated.StaticInstGenClass
	///<inheritdoc cref="T:LibEternal.Generated.StaticInstGenClass"/>
	public partial class Static
	{
		/// <summary>
		///  A roslyn source-generator generated instance that will be used as the target for static instance members
		/// </summary>
		[System.Runtime.CompilerServices.CompilerGenerated]
		private static readonly LibEternal.Generated.StaticInstGenClass Instance = new();

		///<inheritdoc cref="P:LibEternal.Generated.StaticInstGenClass.GetSetIntProperty"/>
		public static int GetSetIntProperty
		{
			get => Instance.GetSetIntProperty;
			set => Instance.GetSetIntProperty = value;
		}

		///<inheritdoc cref="F:LibEternal.Generated.StaticInstGenClass.IntField"/>
		public static int IntField
		{
			get => Instance.IntField;
			set => Instance.IntField = value;
		}

		///<inheritdoc cref="F:LibEternal.Generated.StaticInstGenClass.SystemRandomField"/>
		public static System.Random SystemRandomField
		{
			get => Instance.SystemRandomField;
			set => Instance.SystemRandomField = value;
		}

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.VoidMethod"/>
		public static void VoidMethod()
			=> Instance.VoidMethod();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.ReturnsAString"/>
		public static string ReturnsAString()
			=> Instance.ReturnsAString();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.F_Of_X(System.Int32,System.Single,System.Double,System.Int32)"/>
		public static double F_Of_X(int a, float b, double c, int x)
			=> Instance.F_Of_X(a, b, c, x);

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.ToBeOrNotToBe"/>
		public static bool ToBeOrNotToBe()
			=> Instance.ToBeOrNotToBe();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.NotAnAsyncTask"/>
		public static System.Threading.Tasks.Task NotAnAsyncTask()
			=> Instance.NotAnAsyncTask();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.AsyncVoid"/>
		public static void AsyncVoid()
			=> Instance.AsyncVoid();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.AsyncTask"/>
		public static async System.Threading.Tasks.Task AsyncTask()
			=> await Instance.AsyncTask();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.GenericAsyncTask``1(``0)"/>
		public static async System.Threading.Tasks.Task<T> GenericAsyncTask<T>(T t)
			=> await Instance.GenericAsyncTask<T>(t);

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.GenericAsyncWithConstraints``1"/>
		public static async System.Threading.Tasks.Task GenericAsyncWithConstraints<T>()
			=> await Instance.GenericAsyncWithConstraints<T>();

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.Simple``1(``0)"/>
		public static T Simple<T>(T t)
			=> Instance.Simple<T>(t);

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.OneComplexParameter``1(``0)"/>
		public static T OneComplexParameter<T>(T t)
			=> Instance.OneComplexParameter<T>(t);

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.ComplexParams``2(``1)"/>
		public static T1 ComplexParams<T1, T2>(T2 t2)
			=> Instance.ComplexParams<T1, T2>(t2);

		///<inheritdoc cref="M:LibEternal.Generated.StaticInstGenClass.VeryComplexInheritance``2(``0,``1)"/>
		public static TBase VeryComplexInheritance<TBase, TInherited>(TBase _base, TInherited inherited)
			=> Instance.VeryComplexInheritance<TBase, TInherited>(_base, inherited);

		///<inheritdoc cref="F:LibEternal.Generated.StaticInstGenClass.ReadonlyField"/>
		public static int ReadonlyField => Instance.ReadonlyField;

		///<inheritdoc cref="P:LibEternal.Generated.StaticInstGenClass.GetOnly"/>
		public static int GetOnly
		{
			get => Instance.GetOnly;
		}

		///<inheritdoc cref="P:LibEternal.Generated.StaticInstGenClass.SetOnly"/>
		public static int SetOnly
		{
			set => Instance.SetOnly = value;
		}

		///<inheritdoc cref="P:LibEternal.Generated.StaticInstGenClass.GetInit"/>
		public static int GetInit
		{
			get => Instance.GetInit;
		}
	} //End class
} //End namespace
